version: "3.8"
services:
  telegram-bot:
#    image: unaimillan/telegram-bot:v1.3.4
    build:
      context: .
      tags:
        - unaimillan/telegram-bot:v1.4.0
    restart: on-failure
    depends_on: [postgres]
    volumes:
      - ./storage:/app/storage
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/stb_db
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "10"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stb_db
    ports:
      - "5432:5432"
