"""Initial

Revision ID: b4e8fb3cc5e0
Revises: 
Create Date: 2023-07-07 01:35:13.403640

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b4e8fb3cc5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kvitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'key', name='unique_kv_item')
    )
    op.create_index(op.f('ix_kvitem_chat_id'), 'kvitem', ['chat_id'], unique=False)
    op.create_index(op.f('ix_kvitem_key'), 'kvitem', ['key'], unique=False)
    op.create_table('tguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lang_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tguser_tg_id'), 'tguser', ['tg_id'], unique=True)
    op.create_table('tiktoklink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('share_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiktoklink_link'), 'tiktoklink', ['link'], unique=False)
    op.create_index(op.f('ix_tiktoklink_share_link'), 'tiktoklink', ['share_link'], unique=False)
    op.create_table('gameplayer',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tguser.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    op.create_table('gameresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['tguser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'year', 'day', name='unique_game_result')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameresult')
    op.drop_table('gameplayer')
    op.drop_index(op.f('ix_tiktoklink_share_link'), table_name='tiktoklink')
    op.drop_index(op.f('ix_tiktoklink_link'), table_name='tiktoklink')
    op.drop_table('tiktoklink')
    op.drop_index(op.f('ix_tguser_tg_id'), table_name='tguser')
    op.drop_table('tguser')
    op.drop_index(op.f('ix_kvitem_key'), table_name='kvitem')
    op.drop_index(op.f('ix_kvitem_chat_id'), table_name='kvitem')
    op.drop_table('kvitem')
    op.drop_table('game')
    # ### end Alembic commands ###
